import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNavbar() {
  return (
    <nav className="text-white flex w-full items-center justify-between border-b bg-black p-4 text-xl font-semibold">
      <div>Gallery</div>
      <div> Sign in</div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TopNavbar />
        {children}
      </body>
    </html>
  );
}
