import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import TopNavbar from "./_components/topnav";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by a loyal subscriber of t3.gg",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <TopNavbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
